# Generated by Django 5.2 on 2025-05-07 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default=None, upload_to='images'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='PostImage',
        ),
    ]
